#! /bin/bash

# argument 1 = directory of source forest
# argument 2 = directory of target forest
# argument 3 = size of sub forest

# remove the directory if it already exists
if [[ -e "$2" ]]; then
    rm -rf $1;
fi;

# re-create the target directory
mkdir -p "$2"

# create symbolic links

ln -s "$1/node.dat" "$2/node.dat"

for i in $(seq $3); do
    let a=i-1;
    ln -s "${1}/tree.${a}" "${2}/tree.${a}";
done


    
